# Kubernetes Manifest file - Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: whalephp
  replicas: 3
  template:
    metadata:
      labels:
        app: whalephp
    spec:
      containers:
      - name: whalephp
        image: contosocontainerregistry24744.azurecr.io/myimage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
